#!/bin/sh
set -eu

lb config noauto \
  --mode ubuntu \
  --distribution noble \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main restricted universe multiverse" \
  --bootappend-live "boot=live components quiet splash username=lolly hostname=lollyos locales=hu_HU.UTF-8"
